### ISSUE TITLE
Error occurred while Style/RedundantReturn cop was inspecting

### ISSUE THREAD

**Issue by bmckeough** [bbatsov/ruby-style-guide#607]
I encountered the following error and am reporting it as requested by the error message.

```
user_name@GM23893 project_name [introduce_rubocop_with_exceptions@ac4c6153e1fc]$ rubocop -d app/models/findy.rb
For /Users/user_name/Projects/project_name: configuration from /Users/user_name/Projects/project_name/.rubocop.yml
Inheriting configuration from /Users/user_name/Projects/project_name/.rubocop_todo.yml
Default configuration from /Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/config/default.yml
Inheriting configuration from /Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/config/enabled.yml
Inheriting configuration from /Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/config/disabled.yml
Inspecting 1 file
Scanning /Users/user_name/Projects/project_name/app/models/findy.rb
An error occurred while Style/RedundantReturn cop was inspecting /Users/user_name/Projects/project_name/app/models/findy.rb.
undefined method `type' for nil:NilClass
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:79:in `check_branch'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:109:in `check_if_node'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:82:in `check_branch'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:110:in `check_if_node'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:82:in `check_branch'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:110:in `check_if_node'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:82:in `check_branch'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:110:in `check_if_node'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:82:in `check_branch'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/style/redundant_return.rb:75:in `on_method_def'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/mixin/on_method_def.rb:9:in `on_def'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/commissioner.rb:41:in `block (2 levels) in on_def'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/commissioner.rb:96:in `with_cop_error_handling'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/commissioner.rb:40:in `block in on_def'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/commissioner.rb:39:in `each'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/commissioner.rb:39:in `on_def'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/commissioner.rb:45:in `on_begin'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/ast_node/traversal.rb:141:in `on_while'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/commissioner.rb:45:in `on_module'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/commissioner.rb:45:in `on_begin'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/ast_node/traversal.rb:141:in `on_while'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/commissioner.rb:45:in `on_module'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/ast_node/traversal.rb:12:in `walk'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/commissioner.rb:58:in `investigate'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/team.rb:120:in `investigate'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/team.rb:108:in `offenses'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cop/team.rb:51:in `inspect_file'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:243:in `inspect_file'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:190:in `block in do_inspection_loop'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:222:in `block in iterate_until_no_changes'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:215:in `loop'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:215:in `iterate_until_no_changes'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:186:in `do_inspection_loop'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:101:in `block in file_offenses'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:111:in `file_offense_cache'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:99:in `file_offenses'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:90:in `process_file'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:65:in `each'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:65:in `reduce'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:65:in `each_inspected_file'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/runner.rb:36:in `run'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cli.rb:71:in `execute_runner'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/lib/rubocop/cli.rb:27:in `run'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/bin/rubocop:13:in `block in <top (required)>'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/user_name/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.44.1/bin/rubocop:12:in `<top (required)>'
/Users/user_name/.rbenv/versions/2.2.2/bin/rubocop:23:in `load'
/Users/user_name/.rbenv/versions/2.2.2/bin/rubocop:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Style/RedundantReturn cop was inspecting /Users/user_name/Projects/project_name/app/models/findy.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.44.1 (using Parser 2.3.1.4, running on ruby 2.2.2 x86_64-darwin15)
Finished in 0.18909487800556235 seconds
```

**Comment by ojab** [comment]
This should go to https://github.com/bbatsov/rubocop issues.

**Comment by bbatsov** [comment]
Indeed.
